// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGXmCptDPZy63XaJo-ke1KmZc5Yv31xY8',
    appId: '1:50601780855:web:b52240e425d74a387a4872',
    messagingSenderId: '50601780855',
    projectId: 'depi-project-c20c4',
    authDomain: 'depi-project-c20c4.firebaseapp.com',
    storageBucket: 'depi-project-c20c4.firebasestorage.app',
    measurementId: 'G-24MTDH1E7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgNHN6AKy-HiQu1bEQ7W2FrbQjjbnrXQ',
    appId: '1:50601780855:android:472a5097a92ec83e7a4872',
    messagingSenderId: '50601780855',
    projectId: 'depi-project-c20c4',
    storageBucket: 'depi-project-c20c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWtt3RdEuq_TQQVW_o5QQPXE_NH062YpU',
    appId: '1:50601780855:ios:01d6401e0aa807737a4872',
    messagingSenderId: '50601780855',
    projectId: 'depi-project-c20c4',
    storageBucket: 'depi-project-c20c4.firebasestorage.app',
    iosBundleId: 'com.example.depiProject',
  );
}
